### ISSUE TITLE
Missing getter function for template proposals array 

### ISSUE THREAD

**Issue by sangheraio** [PolymathNetwork/polymath-core-deprecated#100]
Should be able to view all template proposals on a ST with a getter

**Comment by adamdossa** [comment]
(from Slack)
I think we should def. emit an event when a templateProposal or offeringProposal is cancelled (e.g. in `cancelTemplateProposal` and `cancelOfferingProposal`).

In terms of how the API will track the index, there are a couple of options:
1. have the proposeTemplate/OfferingContract include the index in the logged event. The frontend can then poll events to get the relevant index if it needs to cancel.
2. change these variables from being `mapping(address => address[])` to `mapping(address => (mapping address => bool))` and then allow the frontend to cancel based on just knowing the templateProposal / offeringContract addresses.
3. add a function like:
```
function getAllTemplates(address _securityToken) public constant returns (address[] results) {
      return templateProposals[_securityToken];
    }
```
which returns the entire array of template proposals (and similiar for offeringContracts) which the front-end can then loop over. This has a possible attack vector in that if the array grows too large it will not be possible to return it as the required gas could exceed the block gas limit I believe.
[10:05 AM]
1. would be the smallest change if we want to include it in V1, but 2. may be a better long term data structure to use for V2 etc.
[10:06 AM]
Or we could do 1. and 3. in V1 (both simple, "read-only" changes) and then move to 2. in V2 perhaps (acknowledging that 3 is not perfect as it has the above attack vector).

**Comment by pabloruiz55** [comment]
I'm working on implementing 1 and 3.
