### ISSUE TITLE
in SecurityToken.sol 2 events log the wrong address 

### ISSUE THREAD

**Issue by davekay100** [PolymathNetwork/polymath-core-deprecated#107]
event LogNewWhitelistedAddress(address _KYC, address _shareholder, uint8 _role);
    event LogNewBlacklistedAddress(address _KYC, address _shareholder);

both are designed to log KYC address, but the functions in the code actually pass the owner address instead of the KYC address

**Comment by satyamakgec** [comment]
both operations are performed by the owner only not by the KYC so I think there is no need of the _KYC address in the event.

**Comment by adamdossa** [comment]
On this, and other similar events I think we should be indexing the address fields to make it easier to filter for them on the front-end etc.

**Comment by adamdossa** [comment]
@satyamakgec I think keeping the KYC provider address as part of the log is useful (esp. when we have multiple KYC providers). Could you also do a quick review of all events and check that where appropriate we are indexing the address fields? This makes it a lot easier for the front-end to filter / lookup events for individual users (e.g. addresses).

**Comment by satyamakgec** [comment]
Yes, you are right but for the current version, we are sending msg.sender in the _KYC field of the event which is not the KYC address it is the owner address. In that case, we need to send the KYC address that securityToken have
