### ISSUE TITLE
In SecurityTokenRegistrar.createSecurityToken _host should not be a parameter

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#112]
SecurityTokenRegistrar.createSecurityToken takes a _host parameter which is the address which will receive the POLY paid by issuers to create the ST.

I think this is a security concern as the issuer of the ST is the one choosing the _host that will receive their POLY. They could enter an address in their control if using the smart contract directly. 

_host should be a constructor parameter of SecurityTokenRegistrar, which should point to an address controlled by Polymath HQ.

@adamdossa @Everhusk @SatyamSB thoughts?

**Comment by satyamakgec** [comment]
If the user doesn't use our polymath-app wizard to create the securityToken then YES there are high chances that issuer could enter their controlled address if they want.

**Comment by pabloruiz55** [comment]
Even then, it's a high security concern. There's a phishing risk, and also one of us developers could change the hardcoded _host param, deploy the app and get a hold of POLY fees paid before someone notices it.

**Comment by adamdossa** [comment]
I agree - this should not be a parameter to the create function, but should be an address created in the constructor. Presumably the same logic applies to the `_fee` variable as well, to avoid people using 0 as this (and effectively bypassing the fee).

On a related note, is there an objection to having the SecurityTokenRegistrar having an `owner` which could then change these values? I can see that it is possible that PolyMath may want to change the `_fee` and `_host` over time.

**Comment by satyamakgec** [comment]
@adamdossa Yes we can hardcode _host & _fee those values to avoid phishing risk but then no other third parties can use our contracts to build the similar application if we hardcode or imposed any governance model.

**Comment by pabloruiz55** [comment]
@satyamakgec We are talking about having _host and _fee entered by the owner of SecurityTokenRegistrar. 
If a 3rd party wanted to build a similar application using our contracts, they would deploy their own SecurityTokenRegistrar. 

Otherwise, we would have to make SecurityTokenRegistrar hold a list of authorized _hosts for issuers to select.

**Comment by satyamakgec** [comment]
@pabloruiz55 yes both are good way

**Comment by adamdossa** [comment]
@satyamakgec I'm going to take this issue as I'm working on a bunch of core fixes today so will include this.
