### ISSUE TITLE
`setSTO` function should check that address is a contract

### ISSUE THREAD

**Issue by adamdossa** [PolymathNetwork/polymath-core-deprecated#114]
The function currently checks:  
`require(_STOAddress != address(0));`

We could also check that the `_STOAddress` is a contract (has code).

Related note - I think this function should be renamed to:
`setOfferingContract`
to be a little more consistent.

**Comment by pabloruiz55** [comment]
Sounds good to me

**Comment by sangheraio** [comment]
This isn't necessary once STO's become factory based.
