### ISSUE TITLE
`totalRaised` not used / maintained

### ISSUE THREAD

**Issue by adamdossa** [PolymathNetwork/polymath-core-deprecated#115]
`TemplateReputation` has a `totalRaised` variable, but this is not incremented anywhere AFAICT.

Probably this should be incremented in `issueSecurityTokens`

**Comment by pabloruiz55** [comment]
Also, would it keep track of ETH raised? POLY raised? It is really necessary to keep track of this?

Sounds like we could abstract all these "reputation" stuff into a separate contract that keeps track of usage metrics.

@Everhusk

**Comment by sangheraio** [comment]
We could add a function in Template.sol to getTotalRaised(address _securityToken) which pulls the latest numbers from the ST contract.

I think we could also remove this, from a UI perspective reputation is better displayed through the types of SecurityTokens it was used for (which could also sum the total raised from there). This can already be done through usedBy[].
