### ISSUE TITLE
`setRegistrarAddress` can be called multiple times by anyone

### ISSUE THREAD

**Issue by adamdossa** [PolymathNetwork/polymath-core-deprecated#117]
It is possible for anyone to change the `STRegistrar` variable by:
  - calling it with `_STRegistrar` as address(0)
  - calling it again with a new `_STRegistrar` value

**Comment by pabloruiz55** [comment]
Let's add a second require:
require(_STRegistrar != address(0));
Also, the function name has a typo.
It says `setRegsitrarAddress` instead of `setRegistrarAddress`

**Comment by adamdossa** [comment]
Yep - both of these fixed in PR:
https://github.com/PolymathNetwork/polymath-core/pull/119
