### ISSUE TITLE
ST Issuer's POLY can get stuck in ST contract forever

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#121]
For the ST to be able to select a template, it has to posses POLY so it can allocate the Delegate's fee for that template.

Given that this has to be done before the STO starts, the only way for the ST to hold POLY is that the Issuer manually sends POLY to it. The way to do that would be for the Issuer to initiate a Transfer to the ST contract.

Once a template has been selected, the POLY the contract has (which has not been added to allocations as it was transferred directly) gets locked in the contract for the Issuer so they can't drain the contract from POLY.

The problem is that if the Issuer sent 1000 POLY and the template fee was 500. Once the template is selected, the 500 POLY the issuer sent in excess will get locked in the contract forever as he has no way of withdrawing them.

@adamdossa could you check this?

**Comment by adamdossa** [comment]
Yep - agree w/ your analysis.
Possible solution - allow the owner (i.e. issuer) to always withdraw any unallocated balance of POLY in the ST contract. WDYT? Another approach would be for the owner / issuer to only approve an amount of tokens for the ST address, and the ST then transfers the exact amount to cover fees etc. when an auditor / template is selected.

Of the two, the second approach seems simpler, but could still lead to problems if the owner / issuer ignores the protocol and 'accidently' transfers excess POLY to the contract...

**Comment by sangheraio** [comment]
I like the first approach better. The reason we designed it this way originally is to allow the host to subsidize the cost of creating a security token by paying the fee for the issuer.
