### ISSUE TITLE
Decoupling ST/STO - Remove tokensIssuedBySTO from ST contract

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#146]
ST has a variable name `tokensIssuedBySTO` which is only used for checking the following:

```
// ST being issued can't be higher than the totalSupply
require(tokensIssuedBySTO.add(_amountOfSecurityTokens) <= totalSupply);
```

`tokensIssuedBySTO` should be removed and a check in STO should be added so the STO can't put more tokens than available on sale.

**Comment by adamdossa** [comment]
Since tokens aren't actually being minted (they are being transferred from the Offering contract to the contributors) do we need this check at all? The transfer function will already check that the Offering contract is not transferring more than its balance, which should be totalSupply?

**Comment by pabloruiz55** [comment]
Yep, that's my reasoning. 
1) It should not be part of ST at all.
2) It should not be part of STO, UNLESS the developer decides to work with mintable STs which we are not supporting ATM.

**Comment by adamdossa** [comment]
Yep - lets get rid of it.
