### ISSUE TITLE
White list check also need be in  issueSecurityToken() ?  

### ISSUE THREAD

**Issue by satyamakgec** [PolymathNetwork/polymath-core-deprecated#15]
@Everhusk  
A small query. contributor in issueSecurityToken() should also be whitelisted as well otherwise contributor doesn't able to contribute to STO but currently, we are not doing this.  please confirm so I will add this check as well. 

https://github.com/PolymathNetwork/polymath-core/blob/dfced87fa3588e7948c83a6c68306d80af4622bb/contracts/SecurityToken.sol#L252-L261

**Comment by sangheraio** [comment]
Nice catch, yes let's add this in.

**Comment by satyamakgec** [comment]
Okay

**Comment by satyamakgec** [comment]
Done
