### ISSUE TITLE
Offering Factory::proposeOffering allows to propose same offering multiple times

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#154]
Just as #153  , a factory can be proposed multiple times and it will get added repeatedly to the array.

@adamdossa What do you think is the most straightforward way to solve this?
I can think of two ways:

1- Loop through the array to make sure there isn't another element with the same address.
2- In addition to (or instead of ?) having an array, have a mapping that keeps track of the proposals by address and we check that the address is null before attempting to add a new proposal.

**Comment by satyamakgec** [comment]
yes, @pabloruiz55 second way is the best way to do so. complexity is less i.e O(1) 
`mapping(address => bool) public proposedTemplatesList`

**Comment by adamdossa** [comment]
I guess first thing to mention is that proposing the same factory / template multiple times doesn't actually cause any issues AFAICT.

In general though, I agree with @satyamakgec that a mapping is the best option (looping over the array wouldn't work if the array grows too large).
