### ISSUE TITLE
No need of _owner in changeNameSpace?

### ISSUE THREAD

**Issue by satyamakgec** [PolymathNetwork/polymath-core-deprecated#161]
`_owner` can be replaced by the `msg.sender`

**Comment by pabloruiz55** [comment]
CreateNamespace should also set the owner to msg.sender, we don't want someone registering a namespace and mistakenly put someone else as the owner.

**Comment by satyamakgec** [comment]
in changeNameSpace what is our agenda to change the fee or owner as well as because for now, we are changing both? I suppose we only require to change the fee only

**Comment by satyamakgec** [comment]
fix in #170
