### ISSUE TITLE
emit Transfer event when changing totalSupply in securityToken & need check _totalSupply>0

### ISSUE THREAD

**Issue by satyamakgec** [PolymathNetwork/polymath-core-deprecated#167]

**Comment by pabloruiz55** [comment]
Not sure about this. Given that the token would not be "live" yet, don't know if it makes sense to emit the Transfer event. 
@adamdossa what are your thoughts?

**Comment by satyamakgec** [comment]
As @adamdossa proposed earlier that it would be needed for exchange as we are also emitting the event at the time of creation of ST

**Comment by adamdossa** [comment]
Hmm - this is a good point. AFAICT it would be possible for the owner to:  
1. initialise totalSupply to 100.
2. transfer 50 tokens to person b.
3. change totalSupply to 200.

This would result in 250 tokens (since the owner would have a balance of 200 and person b would still have 50).

Maybe being able to change the total supply isn't a good thing and it would be better to include a burn / mint function instead? 

(with the burn / mint function only being usable before the offering has started)

**Comment by adamdossa** [comment]
(with the burn / mint function only being usable before the offering has started)

**Comment by pabloruiz55** [comment]
IMHO we should remove all these functions that allow the modification of the token data.
The UI should be in charge of storing the data entered locally up to the point where the user wants to finalize the token creation and then save the data on the blockchain. From then on, the token is final and no data can be changed, if they wanted to change it, they would just create a new token and pay the fees again.

**Comment by adamdossa** [comment]
Yeah - I am coming round to this POV. Initial thinking is that we didn't want to put people off generating STs by locking everything in stone upfront, but in practice they could just regenerate their token (and possibly ask for their initial POLY fee to be refunded). Certainly totalSupply should be removed. For decimals & name (which are really just display artifacts) I guess it is less dangerous to change, but maybe simpler just to pull this all out.

**Comment by pabloruiz55** [comment]
@adamdossa name is just for display, but decimals could potentially have some implications just as totalSupply does.
If you are ok with that, I'd rather take the simpler approach and have those functions removed.

**Comment by adamdossa** [comment]
Yep - will put this through in a PR today. You've convinced me ;-).

**Comment by satyamakgec** [comment]
fix in #177
