### ISSUE TITLE
any role type customer get verified for now

### ISSUE THREAD

**Issue by satyamakgec** [PolymathNetwork/polymath-core-deprecated#169]
the role should be in range 1 to 4, not any other number

**Comment by pabloruiz55** [comment]
At some point @Everhusk said that there could be many more than 4 roles.

**Comment by satyamakgec** [comment]
Then i think we need to define the range 1 - 15 or any. to make the role authentic

**Comment by satyamakgec** [comment]
no need to check the role as role will more than 4
