### ISSUE TITLE
PolyToken totalSupply is incorrect

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#17]
@satyamakgec beware that the PolyToken being used here has some issues.
The totalSupply is being set incorrectly as the decimals are not being used.

**Comment by satyamakgec** [comment]
Yes it is only for testing for now

**Comment by pabloruiz55** [comment]
Reopening this so we don't forget

**Comment by sangheraio** [comment]
Let's remove this tomorrow when poly-distribution is deployed.
