### ISSUE TITLE
Offering factory can be proposed to ST even if it's not registered via registerOfferingFactory

### ISSUE THREAD

**Issue by bshevchenko** [PolymathNetwork/polymath-core-deprecated#174]

**Comment by pabloruiz55** [comment]
Yeah, you are right. We should probably enforce that the offering contract can only be deployed by the corresponding factory address.
@adamdossa  ?

**Comment by adamdossa** [comment]
One possible approach is to get rid of the "register" step. Then when you propose an offering factory it creates a reputation (if it doesn't already exist) and checks the offering factory validity (i.e. the checks currently done in the "register" step).

**Comment by adamdossa** [comment]
If no one has any objections I can put in the above change.

**Comment by satyamakgec** [comment]
@adamdossa yes that is the possible approach

**Comment by adamdossa** [comment]
I took a slightly different approach in:
https://github.com/PolymathNetwork/polymath-core/pull/177

This issue exists for both Templates and OfferingFactories - both can be proposed without having first been created / registered through Compliance.sol (i.e. a Template could be created elsewhere, then proposed in Compliance.sol). I changes the code to overload a part of the reputation to record that a Template / OfferingFactory has been created / registered through Compliance.sol before allowing it to be proposed for any ST.
