### ISSUE TITLE
There is no way to retrieve namespace fee value

### ISSUE THREAD

**Issue by bshevchenko** [PolymathNetwork/polymath-core-deprecated#175]

**Comment by satyamakgec** [comment]
There is a function called `getNameSpaceData` to retrieve the fee and owner of the namespace, may be you are using an old version of master.
https://github.com/PolymathNetwork/polymath-core/blob/b127ff0033b09e989244762a3bf01b9e45c8296b/contracts/SecurityTokenRegistrar.sol#L187

**Comment by bshevchenko** [comment]
@satyamakgec then we need to deploy new contracts, but it's not urgent since we hardcoded namespace in the polymath-app

**Comment by satyamakgec** [comment]
Once we finalize with the v2 then you can change it.
