### ISSUE TITLE
No use of `if` statement. if it will be written as of now. 

### ISSUE THREAD

**Issue by satyamakgec** [PolymathNetwork/polymath-core-deprecated#179]
I think we mistakenly added the extra statement at line 302
https://github.com/PolymathNetwork/polymath-core/blob/8027a0bc6ec44bd61d3869a1e4a9b6b6a2b2cfd1/contracts/Compliance.sol#L298-L302

**Comment by pabloruiz55** [comment]
Yes, it seems like it. While you are at it, instead of `if (xxx == false)` please change it to `if (!xxx)`
