### ISSUE TITLE
Polymath-core should be built into an NPM package

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#18]
When creating a new custom STO as suggested in Polymath-core readme file, the user has to copy the contracts directory into their own project, which is very prone to errors and it makes it impossible for them to keep track of updates.

I recommend structuring these libraries as Open-Zeppelin does so the files can be easily added to any project by installing an NPM package.

**Comment by satyamakgec** [comment]
Yes we have the same plan , i strongly recommend to create a new repo over the github as STOStandards repo . Today i will create it
