### ISSUE TITLE
Allocations vs balances - Compatibility with ERC20

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#19]
SecurityToken assigns balance[msg.sender] on the constructor equal to the totalSupply. 
Them, it assigns allocations[msg.sender] = 0;

As far as I understand, an STO contract will issue (mint) tokens by calling issueSecurityTokens().
This function MUST update totalSupply if new tokens are being generated.

There's also a disconnect with the balances. The ERC20-like functions (transfer, transferFrom,etc) in SecurityToken check balances[address] but those values are never updated. How does an account get a hold of balances?

**Comment by satyamakgec** [comment]
Yes, you are right balances need to updated

**Comment by satyamakgec** [comment]
fix  b958bc1
