### ISSUE TITLE
change return statement of getDescription() in NameSpaceRegistrar.sol

### ISSUE THREAD

**Issue by satyamakgec** [PolymathNetwork/polymath-core-deprecated#196]
https://github.com/PolymathNetwork/polymath-core/blob/640c6213f03bba367f0d71eb554e07cca7fc001d/contracts/NameSpaceRegistrar.sol#L102-L103

I think instead of this `return (symbolDescription[_nameSpace][_symbol], symbolDescription[_nameSpace][_symbol]);` it should be ` return (symbolDescription[_nameSpace][_symbol], symbolContact[_nameSpace][_symbol]);`

**Comment by adamdossa** [comment]
Good catch!

**Comment by satyamakgec** [comment]
fix #200
