### ISSUE TITLE
issueSecurityTokens() transfer tokens

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#22]
Instead of doing:
```
balances[owner] = balances[owner].sub(_amountOfSecurityTokens);
balances[_contributor] = balances[_contributor].add(_amountOfSecurityTokens);
```    

The transfer() function should be used which also logs the Transfer event.

**Comment by satyamakgec** [comment]
We can use transferFrom() not transfer() but in that case we need to provide the approval for the securities token contract to spend the securities token instead of the owner. what are your thoughts over it as per the security aspects

**Comment by pabloruiz55** [comment]
Yeah, you are right, let's leave it as it is.
