### ISSUE TITLE
Anyone can become a KYC provider (if they have POLY) and we can't remove them.

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#24]
By calling Customer.newProvider() any account can become a KYC provider if they have enough POLY tokens to pay the fee.

I think there SHOULD be a way to either whitelist / blacklist KYC providers or some function to remove them/make them unavailable.

If a KYC provider goes rouge we currently don't have any way to remove them from the system or prevent from them being used.

**Comment by satyamakgec** [comment]
yes agreed , i think we are managing this stuff only by our application view by removing them from our application but yes we need to work on smart contracts to add this extensive functionality.

**Comment by pabloruiz55** [comment]
This could be solved in a different few ways, but here's the only I like the most:

1. KYC providers can sign up by calling newProvider() as it is now, but we add a bool "active" field to the Provider struct, starting as false.
2. Whenever the KYC provider is used, we first check they are active
3. The owner of Customers. sol can set active to true or false for each KYC provider as they are onboarded.

This way, even if we have many different KYC providers signing up, they can't be used until they are enabled. And if there's a problem with one of them, they can be disabled.

**Comment by satyamakgec** [comment]
for issue #58 #26 #24 @pabloruiz55 @adamdossa  review 1227192 . For withdrawal Poly from `Customers.sol` I use _to address (for now). I think keeping POLY to owner address is not safe because many other functions also being called by it. (someone operates those functions with polymath admin wizard). Do we hardcode the _to address or this address should be Polymath Multisig?

**Comment by sangheraio** [comment]
@pabloruiz55  Polymath shouldn't be able to make any decisions on who can and can't participate in the network. It needs to be decentralized.

The fee was added in to prevent spam, but I think it might be best to just take this fee out.

We could potentially have the funds go towards a KYC research fund? Identity hackathons, etc.

**Comment by satyamakgec** [comment]
I left the changeRegisterationFee() function to change the providerFee called only by the owner or should I remove it as well. @Everhusk ?

**Comment by pabloruiz55** [comment]
@satyamakgec changed this so now there's no fee for KYC providers to add themselves and there's no owner to this Customers.sol contract due to some other issues posted. For example: #26 
I don't think this is good. Anyone could add themselves (or even someone else) as a KYC provider for free, without any consequences. An then, we don't even have the means to take a bad actor out of this contract.

I think we should still have Customers.sol have an owner who can remove KYC providers if they want, or at least disable them while they are investigated.

This would also require thinking about what happens with actors verified by a KYC provider that is currently disabled.
