### ISSUE TITLE
Streamline the way we check for null address

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#25]
Sometimes `require(address != address(0));` is used while sometimes `require(address != 0x0);` is used instead.

I personally prefer `require(address != address(0));` but we should stick with one.

For example in Customer.newProvider()
```
require(_providerAddress != address(0));
require(_details != 0x0);
```

**Comment by satyamakgec** [comment]
For addresses we are using `require(address != address(0))` and for bytes32 we are using `require(bytevalue != 0x0)` so `_details` is bytes32 type we can't use `address(0)` because of mismatch conversion 
 fix in 
3eb2b54
