### ISSUE TITLE
Customer.sol newProviderFee can't be modified.

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#26]
There's no way to change the Customer.newProviderFee, which is set to be 1000 POLY.
There should be an owner for this contract and they should have the ability to modify the entry fee for new providers as 1000 POLY might need to be changed at some point.

**Comment by satyamakgec** [comment]
we have the function
https://github.com/PolymathNetwork/polymath-core/blob/c5dee69f76a03db27389d266023e8d9f8b2476d4/contracts/Customers.sol#L75-L79
providers can change the fee after the successful registration. different kyc-providers have different fees if they want . by default we are using 1000 POLY only

**Comment by pabloruiz55** [comment]
@satyamakgec 
What you shared above is the fee the KYC provider charges the verifying customers.

I mean the fee Polymath charges in POLY to have a new KYC provider added.
`uint256 public constant newProviderFee = 1000;` is the fee in POLY being charged to a new KYC provider by us, and we can't modify it.

**Comment by satyamakgec** [comment]
ohh my bad , i will add this feature also but we need owner also for this i think i need to add ownership functionality as well @Everhusk what is your call do we add ownership stuff in the polymath-core

**Comment by sangheraio** [comment]
Basically the same as what's being discussed in #24 need a plan for poly earned. But yes where these funds go is still TBD. Wanted to lock it away to reduce supply over time, but I this makes it security like. Another option is to send this to a reserve-like wallet and have it re-distributed to efforts that improve the KYC provider network. Although leaning towards just taking it out completely.
