### ISSUE TITLE
indexed removed from LogNewSecurityToken

### ISSUE THREAD

**Issue by satyamakgec** [PolymathNetwork/polymath-core-deprecated#28]
@Everhusk  
i removed the indexed from the event because it creates the problem in running the test cases. 
please have a look into issue.
https://github.com/ethereumjs/ethereumjs-vm/issues/114

**Comment by pabloruiz55** [comment]
From which variable did you remove the indexed attrib.?

**Comment by satyamakgec** [comment]
it is removed from the event 
https://github.com/PolymathNetwork/polymath-core/blob/907b87b5eaa72e9128aadeee522fcf587612c86e/contracts/SecurityTokenRegistrar.sol#L36
previously it was `string indexed _ticker`

**Comment by sangheraio** [comment]
This is fine with me.
