### ISSUE TITLE
Comment on roles needs to be reordered 

### ISSUE THREAD

**Issue by davekay100** [PolymathNetwork/polymath-core-deprecated#33]
the comment below states that the issuer is role 2
https://github.com/PolymathNetwork/polymath-core/blob/c5dee69f76a03db27389d266023e8d9f8b2476d4/contracts/Customers.sol#L84

But we require role 2 to be the delegator here:
https://github.com/PolymathNetwork/polymath-core/blob/c5dee69f76a03db27389d266023e8d9f8b2476d4/contracts/Compliance.sol#L83

Nothing wrong with contracts working properly, just have to switch to have issuer:3 and delegator:2 (or consider removing the role numbers completely, and leaving that to be in the documentation we have). I looked throughout the rest of the contracts and this is the only part that isn't correct for names of roles

**Comment by satyamakgec** [comment]
Everywhere we are using tole 2 for delegate so you are right .
fix b57819b
