### ISSUE TITLE
Polymath.js needs 6 state vars to be labeled public for Templates.sol

### ISSUE THREAD

**Issue by davekay100** [PolymathNetwork/polymath-core-deprecated#37]
Please see the list of state vars below. and note which ones need to be public so we can call them:

    address owner;
    string public offeringType;
    bytes32 public issuerJurisdiction;
    mapping(bytes32 => bool) public allowedJurisdictions;
    mapping(uint8 => bool) public allowedRoles;
    bool public accredited;
    address KYC;
    bytes32 details;
    bool finalized;
    uint256 public expires;
    uint256 fee;
    uint8 quorum;
    uint256 vestingPeriod;

**Comment by satyamakgec** [comment]
which variables you want to access from outside. let me know I will make get methods for them

**Comment by davekay100** [comment]
allowedJurisdictions, allowedRoles, accredited, expires, issuerJurisdiction, and offeringType

however i dont need getter functions written for them, i just need them to be named public, as naming them public will automatically give them getter functions, and i wrote the polymath.js code to access the state vars directly

 (fyi, the code i inserted above is my code, the current polymath core code has none of them labeled public, i should have stated that earlier ).

**Comment by satyamakgec** [comment]
fix  6ed0995
