### ISSUE TITLE
SecurityToken's startSTO & endSTO can be set to values different to the actual STO's start/end times

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#40]
ST. selectOfferingProposal() gets passed startSTO and endSTO parameters which could be different times that those set on an actual STO. 

Either:
1. These get read from the STO contract instead of being set and we eliminate these variables from the ST contract (which IMO they don't belong in the ST contract at all).
2. Or it should be required that the values entered match the values set on the STO.

There's also the issue that there's no way to enforce these two variables stay in sync with the actual STO. As it is, even if we enforce they should match, the owner of the STO could modify the values later on if their contract allows so.

**Comment by satyamakgec** [comment]
How about we make sure at the time of setSTO issuer also needs to enter the endSTO and startSTO parameters and we match them at the time of selectOfferingProposal() and startSTO timestamp should be greater than 1 day from the timestamp of selectingOfferingProposal() to mitigate the the time slack between those function calling and only then offering contract will live?.

I think this way if an owner could modify the date then it also needs to change the STO contract address as well.  
@pabloruiz55

**Comment by pabloruiz55** [comment]
I'm concerned about the duplication of these 2 variables, with the additional concern that the SecurityToken contract should not even care about the STO timeframe.

For example: issueSecurityTokens() requires that  now > startSTO and now < endSTO. That logic should be actually part of the STO. The STO should handle whether or not the token sale is "open" or "closed". 

At the very least, setSTO should set the startSTO / endSTO variables by accessing them from STO and not be manually inputed.

Looping @adamdossa for his input.

**Comment by satyamakgec** [comment]
Agreed though that process we can remove startTime and endTime parameters from the `selectOfferingProposal`. Yes, that will be the better way compare what we have now.

**Comment by adamdossa** [comment]
I guess the key question here is whether the compliance delegate should control the period during which tokens can be issued (in return for POLY) - effectively the start / end time of the ICO.

In general it looks like the compliance delegate is not really responsible for details around the security token offering (as opposed to the security token) in the current framework, although arguably this is important from a compliance perspective as well (and is somewhat implied by the name `selectOfferingProposal`).

My guess is that the correct logic here is that the offering proposal should be linked to the STO, not the ST, and then the delegate is effectively signing off on both the ST and the STO - what do you think? I realise this would be a significant change - WDYT @pabloruiz55 @Everhusk 

In the short term I 100% agree that these variables should only exist in one place as per the proposed fix.

**Comment by sangheraio** [comment]
Yes this is correct, STO contract best practice will need to ensure they match. We could also add a require() for this in the STO standard to make only the SecurityToken contract able to call this function. 

Let's add an onlyST modifier in the securityTokenOffering() function in STO contracts.
