### ISSUE TITLE
Why are we checking SecurityToken contract has POLY balance to execute selectOfferingProposal()?

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#41]
In ST.selectOfferingProposal() there's this line:

`require(POLY.balanceOf(this) >= allocations[delegate].amount + _fee);`

What's the idea of that? 

Additionally, even though we are checking for such POLY balance within the ST contract, there's no transfer of POLY being done from it to the delegate.

**Comment by satyamakgec** [comment]
Because the securityToken contract has to pay the fee to them after the successful issuance of the security token. We are enforcing the ST contract that it has that much amount of poly in its reserve to give payout to delegates their fees(for template approval) and payout to STO auditor (for STO development)

**Comment by pabloruiz55** [comment]
But where are we actually doing the payment?
If we are not doing it within the function that is checking the balance, then it doesn't make much sense.
Even if at that point it does have the balance, nothing stops the owner from draining the contract out of POLY after calling the function, before the payment is done somewhere else.

**Comment by adamdossa** [comment]
My reading is that since the delegate and auditor are assigned before issuance starts, it ensures the contract has been seeded with enough POLY to pay these entities.

Payment would be through the usual withdrawPoly function (once the vesting on these allocations has completed).

**Comment by satyamakgec** [comment]
yes @adamdossa is correct
