### ISSUE TITLE
SecurityToken's transferFrom requires the msg.sender to be whitelisted

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#45]
While `transfer()`'s only requirement (in terms of being whitelisted) is that the recipient is whitelisted (marked as allowed in sharehoders mapping), transferTo requires in addition that the msg.sender be in that whitelist as well.

If transfer can be initiated without being in the whitelist, why shouldn't it be the same for transferFrom ?

**Comment by satyamakgec** [comment]
it is already there 
https://github.com/PolymathNetwork/polymath-core/blob/8c5b153832fde8c829f1f5f56351b7b0524f67d0/contracts/SecurityToken.sol#L319

**Comment by pabloruiz55** [comment]
My point is that it should not work like that. See @adamdossa 's comment on this:

>  - should `transferFrom` insist that the msg.sender is whitelisted? `approve` / `transferFrom` is used to allow a 3rd party to transfer tokens on your behalf, but that 3rd party never owns the tokens. The 3rd party may for example be a smart contract or exchange - is there a requirement that the 3rd party has been KYC’ed / whitelisted?
