### ISSUE TITLE
TBD: There should be a way for the Issuer to override the KYC to get an investor verified/whitelist

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#47]

**Comment by Everhusk** [comment]
Yes this is correct, STO contract best practice will need to ensure they match. We could also add a require() for this in the STO standard to make only the SecurityToken contract able to call this function. 

Let's add an onlyST modifier in the securityTokenOffering() function in STO contracts.

**Comment by sangheraio** [comment]
Yes I agree, we should add in the ability for an issuer to add additional KYC providers.

**Comment by pabloruiz55** [comment]
This doesn't refer to the possibility of having multiple KYC providers, but rather to having the issuer have the ability to bypass the KYC provider and add an account to the whitelist under their own liability. This is related to what was added on Asana last night: 

> Previously, your team had this idea that KYC providers would be the ones that maintain the whitelists of investors, and as such, they would be the gatekeepers of the ecosystem.  This doesn't work for a number of reasons.  First, KYC/AML folks will not take the liability for that.  Second, as Polymath has experienced first-hand, they suck.  The users of KYC (exchanges, issuers, etc.) have to be the ones that maintain the whitelist and they need the ability to decide not to KYC someone or to pass someone through themselves.  Or...they might fail someone at their own discretion.  If you think about it, this is how the existing world already works.

**Comment by sangheraio** [comment]
Well it would have to be done in a two step process, Issuer create a new KYC provider (themselves), adds it to the list of ST KYC providers, verifies an investor, then adds them to the whitelist.

**Comment by pabloruiz55** [comment]
We already added the following to `addToWhitelist()`:
`require(KYC == msg.sender || owner == msg.sender);`

So, the issuer is able to add someone to the whitelist. What we would need to do is to add an if branch there stating that if the msg.sender is the issuer/owner, then it shouldn't need to do all those verifications, just add it to the whitelist. 
What do you think? @adamdossa @Everhusk

**Comment by pabloruiz55** [comment]
Actually, that doesn't work as intended. Even though the owner can call the function, the KYC provider is needed to get the customer data. We would not be able to bypass it, as it is.

I guess then, to bypass the KYC provider the issuer could create their own KYC provider and use that, this requires no further changes to the code. (Other than the pending issue regarding having multiple KYC providers).
