### ISSUE TITLE
Change  uint8 role to an Enum for better readability

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#50]
Throughout the contracts we are using role as an uint8, but this is very error prone and requires going to the source file to see which id corresponds to which role.
This could be changed to be a Enum.

**Comment by sangheraio** [comment]
Would be too big of an Enum, leaving it open ended allows for additional functionality to be layered on top. For example, a KYC provider may want to specify certain verification levels on a user. This may vary between providers so better to leave it unbounded.
