### ISSUE TITLE
Should voting use POLY instead of security token balances

### ISSUE THREAD

**Issue by adamdossa** [PolymathNetwork/polymath-core-deprecated#52]
should `contributedToSTO` record the amount of POLY contributed, rather than the corresponding amount of security tokens issued? Since this mapping is used to vote, it may be better to use the POLY amount as this is harder to manipulate by the issuer (the issuer could issue a large number of security tokens to themselves for a small or zero amount of POLY and thus skew the vote). This would also require a corresponding change in `voteToFreeze`.

**Comment by satyamakgec** [comment]
I agree with you, i will make the changes

**Comment by adamdossa** [comment]
You need to also modify the voting function to divide by the correct amount (poly contributed not tokens issued).

**Comment by satyamakgec** [comment]
oops my bad
