### ISSUE TITLE
selectTemplate and selectOfferingProposal may be called multiple times

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#56]
I don't know if this is by design, but being able to call these functions more than once effectively overwrites some critical variables. For example, startSTO/endSTO could be modified by "changing" the offering proposal.

**Comment by satyamakgec** [comment]
We can add a mapping `mapping(_stoContract=>bool)isSTOProposed` to handle the offering contract proposal.  what do you say? @pabloruiz55
