### ISSUE TITLE
No way for PolyMath to pull out POLY fees from providers

### ISSUE THREAD

**Issue by adamdossa** [PolymathNetwork/polymath-core-deprecated#58]
Customers.sol takes a fee for new KYC providers, but I can't see that the contract has any way to extract this fee from the contract (i.e. for contract owner to transfer POLY balance to themselves)?

**Comment by satyamakgec** [comment]
Yes, In that case we need to encapsulate our Customers contract into ownership model. To provide the ownership of the Customer contract to call the function as withdraw POLY and change fee provided by the customer for storing the data on chain.
What do you think?

**Comment by adamdossa** [comment]
Yep - ownership model would work. I think this is a critical bug that should be fixed before audit. @pabloruiz55 @Everhusk agree?

**Comment by satyamakgec** [comment]
This also solve #26 #24

**Comment by pabloruiz55** [comment]
Yes, this is critical. Customers.sol should have an owner that can withdraw the tokens paid to it and change the fee.

**Comment by satyamakgec** [comment]
ok i will make these changes

**Comment by sangheraio** [comment]
Duplicate of #26 and #24, closing.
