### ISSUE TITLE
Template.getTemplateDetails requires that expires > now to return data

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#62]
```
function getTemplateDetails() view public returns (bytes32, bool) {
        require(expires > now);
        return (details, finalized);
    }
```
In order to get the template details it requires not to be expired. It should give its details anyways as well as whether or not it has expired.
This function is not used anywhere yet.

**Comment by satyamakgec** [comment]
This function used to get the template details and finalized state as for the usability purpose I suppose it will be used for UI wizard to get the details of active templates only not expired.
