### ISSUE TITLE
What's the purpose of SecurityTokenRegistrar.sol?

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#64]
SecurityTokenRegistrar is a Factory for SecurityToken.sol, but there is no enforcement for going through STR to create a new ST contract.

If we are going to use STR, then ST should probably require that it must be deployed by STR instead of anyone. Else, we'll have ST contracts that are not registered on the STR.

**Comment by satyamakgec** [comment]
I do not seem any best option to achieve it. possible ways that i think.

- hardcode the STR address in ST contract and then check msg.sender in a constructor. 
- Or add one valid invalid flag that will only be verified by the STR contract.

Share your suggestions.

**Comment by adamdossa** [comment]
Possibly link the ability to withdraw / deposit POLY to the ST contract to the fact that it is deployed by the STR?

**Comment by satyamakgec** [comment]
@adamdossa yep that will be the best way
