### ISSUE TITLE
Should a Template be created on their own?

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#66]
Compliance.sol is in charge of creating new Templates and keeping track of them.

Template.sol does not enforce that only Compliance should create them. Anyone can create their own template but they won't get added to Compliance' templates mapping this way.

I believe Template should only be created by the Factory Compliance.sol.

**Comment by satyamakgec** [comment]
Yes, you are right but I think we will not achieve anything by enforcing the creation of template through compliance only. Because automatically template contracts created through any mean other than compliance will useless anyways.
