### ISSUE TITLE
Is this line returning a whole entire Template instead of just a template address?

### ISSUE THREAD

**Issue by davekay100** [PolymathNetwork/polymath-core-deprecated#71]
https://github.com/PolymathNetwork/polymath-core/blob/907b87b5eaa72e9128aadeee522fcf587612c86e/contracts/SecurityToken.sol#L305

Looks like this is actually returning the whole instance of the Template contract, but the function really wants to return the template address.

Suggestion to fix, make a public state var for templateAddress, then when running selectTemplate(), when you recieve _tempalteAddress, store it in the new state var

**Comment by adamdossa** [comment]
FWIW this would just be implicitly cast to an address in this code. You can do something like address(Template) if you want to explicitly cast.

**Comment by satyamakgec** [comment]
it is working fine
