### ISSUE TITLE
Finalize list of roles

### ISSUE THREAD

**Issue by sangheraio** [PolymathNetwork/polymath-core-deprecated#73]
Create a readme for different role types and remove requirement for delegates to be KYC'd

**Comment by satyamakgec** [comment]
I added the roles readme 0e6f1c4 . To remove the requirement for delegates to be KYC'd, we need to store them in different mapping.

**Comment by Everhusk** [comment]
Readme looks good, can't we just remove the role check here: https://github.com/PolymathNetwork/polymath-core/blob/master/contracts/Compliance.sol#L85 ?
