### ISSUE TITLE
Protocol Changes as defined by Trevor/Jor on 22/1/18

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#79]
On Asana, the following protocol changes were requested:

**- Previous protocol had KYC providers as gatekeepers.  Now they are just service providers and Issuers/exchanges are gatekeepers (just like it works in real life).**
  Previously, your team had this idea that KYC providers would be the ones that maintain the whitelists of investors, and as such, they would be the gatekeepers of the ecosystem.  This doesn't work for a number of reasons.  First, KYC/AML folks will not take the liability for that.  Second, as Polymath has experienced first-hand, they suck.  The users of KYC (exchanges, issuers, etc.) have to be the ones that maintain the whitelist and they need the ability to decide not to KYC someone or to pass someone through themselves.  Or...they might fail someone at their own discretion.  If you think about it, this is how the existing world already works.

**- Previously there was just one master whitelist of investor. Now there can be multiple whitelists.**
  Previously, there was this idea of a master whitelist that would be approved...but the reality is that every deal must have it's own whitelist which is a combination of the parameters of all participants.  For example, an issuer maintains a whitelist, and then an exchange maintains a whitelist, and for someone to be on an exchange trading Polymath, they would need to meet the whitelist conditions of both issuer and exchange.  In reality, this is how it must work as people may have different standards for who they allow or not.

**- Previously we were trying to do things with just an ethereum address. Now we are going to try to hash a legal name along with ethereum address.**
 It's impossible to KYC only an ethereum address as that address can always be used for someone else.  However, if a KYC provider whitelists a person, then the issuer can save that ethereum address to that person.  Then, so long as both fields match, that's pretty reliable indicator that the person behind that is who they claim to be.

What are we doing about these?

**Comment by sangheraio** [comment]
- Previous protocol had KYC providers as gatekeepers. Now they are just service providers and Issuers/exchanges are gatekeepers (just like it works in real life).
This is more of an off chain problem of how to explain what KYC providers are. No code change required.

- Previously there was just one master whitelist of investor. Now there can be multiple whitelists.
#49 fixes this

- Previously we were trying to do things with just an ethereum address. Now we are going to try to hash a legal name along with ethereum address.
This was already done here: https://github.com/PolymathNetwork/polymath-core/blob/master/contracts/Customers.sol#L30
