### ISSUE TITLE
Rework of Jurisdiction whitelisting process

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#80]
Each `Customer` will have both a country jurisdiction code and a subdivision jurisdiction code.

If the country code is whitelisted (maps to true) then jurisdiction is OK (and we don't care about sub-division code).

If the country code is not whitelisted (maps to false) then we check whether the subdivision is whitelisted (maps to true) in which case jurisdiction is OK, o/w it is not OK.

So, with the above, when calling `addJurisdiction`, if an entire country is OK, then you just have to pass the country code, otherwise if only certain sub-divisions are OK then you would need to pass each of the OK sub-divisions (and not pass the country code).

This adds some complexity (customers having country & sub-division codes), but keeps the jurisdiction mapping simple (single mapping, always a whitelist) and minimises transactions for the common case.

If this sounds OK to @Pablo Ruiz @sukhveer @Aidan Hyman then I'll put this in a PR for review.Each `Customer` will have both a country jurisdiction code and a subdivision jurisdiction code.

If the country code is whitelisted (maps to true) then jurisdiction is OK (and we don't care about sub-division code).

If the country code is not whitelisted (maps to false) then we check whether the subdivision is whitelisted (maps to true) in which case jurisdiction is OK, o/w it is not OK.

So, with the above, when calling `addJurisdiction`, if an entire country is OK, then you just have to pass the country code, otherwise if only certain sub-divisions are OK then you would need to pass each of the OK sub-divisions (and not pass the country code).

This adds some complexity (customers having country & sub-division codes), but keeps the jurisdiction mapping simple (single mapping, always a whitelist) and minimises transactions for the common case.

If this sounds OK to @Pablo Ruiz @sukhveer @Aidan Hyman then I'll put this in a PR for review.

**Comment by adamdossa** [comment]
I've changed the code in the above PR if we want to include this in V1. There would need to be corresponding app changes to only add subdivision codes where the corresponding country code was false. @pabloruiz55 @Everhusk

**Comment by pabloruiz55** [comment]
Thanks @adamdossa looks good to me.
I'd add somewhere some clarifications on how this would have to be used.
For example, if there's a country that has at least one jurisdiction that is not allowed, then the country jurisdiction MUST NOT be added, and all jurisdictions save for the one not allowed should be added.

**Comment by sangheraio** [comment]
Closed with #87
