### ISSUE TITLE
Can these 4 mappings be made public so we can easily call them from polymath.js?

### ISSUE THREAD

**Issue by davekay100** [PolymathNetwork/polymath-core-deprecated#82]
Can we make these 4 mappings public, so getter functions are automatically created by the compiler that polymath.js can call into?

https://github.com/PolymathNetwork/polymath-core/blob/0b1676da48b3066ea37331b1af72d0e823f85d18/contracts/SecurityToken.sol#L72

https://github.com/PolymathNetwork/polymath-core/blob/0b1676da48b3066ea37331b1af72d0e823f85d18/contracts/SecurityToken.sol#L73

https://github.com/PolymathNetwork/polymath-core/blob/0b1676da48b3066ea37331b1af72d0e823f85d18/contracts/SecurityToken.sol#L76

https://github.com/PolymathNetwork/polymath-core/blob/0b1676da48b3066ea37331b1af72d0e823f85d18/contracts/Compliance.sol#L33

**Comment by pabloruiz55** [comment]
@davekaj  Sure, just pushed the change. Waiting for reviews to merge.
