### ISSUE TITLE
Make verifying customers more efficient

### ISSUE THREAD

**Issue by adamdossa** [PolymathNetwork/polymath-core-deprecated#88]
Currently, you need to call `verifyCustomer` for each verified customer to add them to the whitelist.

For a large number of verifications this will be expensive.

A batch version of this function would reduce gas a little and make it easier to use.

**Comment by pabloruiz55** [comment]
I don't know if that's possible to do from a user experience point of view. The function requires a transferFrom (which needs the customer to previously have set an allowance to the KYC provider). If we had 30+ calls inside one function call I can picture this function constantly throwing and cancelling the whole operation due to one of those customers not having a proper allowance set.

**Comment by adamdossa** [comment]
True. The KYC provider could check that each customer has approved the correct amount of POLY for each transfer before calling in a batch (which would be non-atomic), or the function itself could check the approved amount before calling transferFrom to avoid throwing (but this would mean a batch may partially fail which would be messy).

Currently the gas cost to verify a single customer is 129,134 so with a gas price of 20GWei so at $1000 per ETH this is around $2.5 to verify each customer which is quite high.

**Comment by pabloruiz55** [comment]
We'd have to check, but I don't think that by doing the verification in a loop we would get much gas reduction. Given the transferFrom and the assignments to the struct I don't think much gas would be saved as there's no operation that can be simplified from that.

I'd do it only for making it a bit less of a pain to verify multiple accounts at the same time, if we can make sure that it won't throw if one of the transferFrom fails.

**Comment by adamdossa** [comment]
Closing as I don't think there is much we can do from this angle at the moment given that a KYC approval involves a POLY transfer and a data payload for the investor.
